# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
#    parameter_name: value

services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]
    HolaService:
        class: AppBundle\Service\HolaService
        arguments: [    ]
    twig.extension.intl:
        class: Twig_Extensions_Extension_Intl
        tags:
            - { name: twig.extension }
    PrimitivaService:
        class: AppBundle\Service\PrimitivaService
        arguments: ["@doctrine.orm.entity_manager"]
    TotalResultsService:
        class: AppBundle\Service\TotalResultsService
        arguments: ["@doctrine.orm.entity_manager"]
    TotalPerMonthService:
        class: AppBundle\Service\TotalPerMonthService
        arguments: ["@doctrine.orm.entity_manager"]
    EuromillonesService:
        class: AppBundle\Service\EuromillonesService
        arguments: ["@doctrine.orm.entity_manager"]